title: One Touch Ltd
description: 'Social media project '
template:
  repo: one-touch-ltd-template
  name: one-touch-ltd
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
